services:
  jbhifi-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jbhifi-container
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
